<?php
return [
    'information' => [
        'phone' => '*123',
        'help_email' => 'help@ase.az',
    ],
    'currency' => 'USD',
    'card_number' => [
        'validation' => '9999-9999-99',
    ],
    'default' => [
        'no-image' => 'uploads/default/no-image.jpg',
        'avatar' => 'uploads/default/avatar.png',
    ],
    'send' => [
        'as' => 'info@ase.az',
        'name' => 'ASE',
    ],
    'warehouse' => [
        'filter' => [
            0 => 'All',
            1 => 'Requested',
        ],
        'cells' => [
            'A' => 6,
            'B' => 6,
            'C' => 6,
            'D' => 6,
            'E' => 8,
            'F' => 8,
            'G' => 8,
            'H' => 8,
            'K' => 8,
            'L' => 8,
            'M' => 6,
            'N' => 6,
            'O' => 4,
            'P' => 6,
            'Q' => 6,
            'R' => 6,
            'S' => 6,
            'T' => 6,
            'U' => 6,
            'X' => 6,
            'Z' => 6,
            'J' => 1,
            'FO' => 1,
            'LN' => 1
        ],
    ],
    'attributes' => [
        'yes_no' => [
            0 => 'No',
            1 => 'Yes',
        ],
        'yes_noWithLabel' => '[{value:0, text:"No"},{value:1, text:"Yes"}]',
        'pagination' => [1 => 1, 5 => 5, 10 => 10, 25 => 25, 50 => 50, 75 => 75, 100 => 100, 250 => 250],
        'currencies' => [
            3 => 'TRY',
            0 => 'USD',
            1 => 'AZN',
            2 => 'EUR',
            4 => 'RUB',
            5 => 'GBP',
            6 => 'CNY',
            7 => 'AED',
            8 => 'KZT',
            9 => 'KRW'
        ],
        'currencies2' => ['TRY' => 3, 'USD' => 0, 'AZN' => 1, 'EUR' => 2, 'RUB' => 4, 'GBP' => 5, 'CNY' => 6, 'AED' => 7, 'KZT' => 8,'KRW' => 9],
        'customsCurrencies' => [
            840 => 'USD',
            932 => 'AZN',
            978 => 'EUR',
            949 => 'TRY',
            643 => 'RUB',
            826 => 'GBP',
            156 => 'CNY',
            784 => 'AED',
            398 => 'KZT',
            728 => 'SSP',
            410 => 'KRW'
        ],
        'currenciesConvert' => [1, 1.7, 0.9068732, 5.97619, 63.3873, 0.764390, 7.28, 378.77, 477.83],
        'length' => ['cm', 'in'],
        'lengthConvert' => [1, 2.54],
        'weight' => ['kg', 'lbs', 'stn'],
        'weightConvert' => [1, 0.45359237, 0.157],
        'cd' => [
            'notDeliveredStatus' => [
                0 => '--',
                //1 => 'NA-No Answer',
                //2 => 'NA-Blocked',
                //3 => 'FD-Future delivery',
                //4 => 'RC-Cancelled',
                //11 => 'WI-Wrong Mobile',
                //28 => 'Wrong address by driver'
                'TTC47' => "Müştəri ilə yenidən təyin edildi",
                'TTC48' => "Müştəri yeri dəyişdirmək istəyir",
                'TTC55' => "Ünvan məlumatı natamamdır",
                'TTC37' => "Müştəridən cavab yoxdur",
                'TTC36' => "Bağlama zədələnib",
                'TTC33' => "Səhv telefon nömrəsi",
                'TTC30' => "Müştəri bağlamadan imtina etdi",
            ],
            'notDeliveredStatusWithLabel' => json_encode([
                ['value' => 0, 'text' => "--"],
                //	    ['value' => 1,'text' => "NA-No Answer"],
                //		['value' => 2,'text' => "NA-Blocked"],
                //		['value' => 3,'text' => "FD-Future delivery"],
                //		['value' => 4,'text' => "RC-Cancelled"],
                //		['value' => 11,'text' => "WI-Wrong Mobile"],
                //		['value' => 28,'text' => "Wrong address by driver"]
                ['value' => 'TTC47', 'text' => "Müştəri ilə yenidən təyin edildi"],
                ['value' => 'TTC48', 'text' => "Müştəri yeri dəyişdirmək istəyir"],
                ['value' => 'TTC55', 'text' => "Ünvan məlumatı natamamdır"],
                ['value' => 'TTC37', 'text' => "Müştəridən cavab yoxdur"],
                ['value' => 'TTC36', 'text' => "Bağlama zədələnib"],
                ['value' => 'TTC33', 'text' => "Səhv telefon nömrəsi"],
                ['value' => 'TTC30', 'text' => "Müştəri bağlamadan imtina etdi"],
            ]),
            'notDeliveredStatusCd' => [
                0 => '--',
                //	1 => 'NA-Cavab yoxdur',
                //	2 => 'NA-Bloklanıb',
                //	3 => 'FD-Gələcək çatdırılma',
                //	4 => 'RC-Ləğv edildi',
                //	11 => 'WI-Səhv Mobil',
                //	28 => 'Sürücü tərəfindən səhv ünvan'
                'TTC47' => "Müştəri ilə yenidən təyin edildi",
                'TTC48' => "Müştəri yeri dəyişdirmək istəyir",
                'TTC55' => "Ünvan məlumatı natamamdır",
                'TTC37' => "Müştəridən cavab yoxdur",
                'TTC36' => "Bağlama zədələnib",
                'TTC33' => "Səhv telefon nömrəsi",
                'TTC30' => "Müştəri bağlamadan imtina etdi",
            ],
            'notDeliveredStatusCdWithLabel' => json_encode([
                ['value' => 0, 'text' => "--"],
                //['value'=>1,'text'=>"NA-Cavab yoxdur"],
                //['value'=>2,'text'=>"NA-Bloklanıb"],
                //['value'=>3,'text'=>"FD-Gələcək çatdırılma"],
                //['value'=>4,'text'=>"RC-Ləğv edildi"],
                //['value'=>11,'text'=>"WI-Səhv Mobil"],
                //['value'=>28,'text'=>"Sürücü tərəfindən səhv ünvan"]
                ['value' => 'TTC47', 'text' => "Müştəri ilə yenidən təyin edildi"],
                ['value' => 'TTC48', 'text' => "Müştəri yeri dəyişdirmək istəyir"],
                ['value' => 'TTC55', 'text' => "Ünvan məlumatı natamamdır"],
                ['value' => 'TTC37', 'text' => "Müştəridən cavab yoxdur"],
                ['value' => 'TTC36', 'text' => "Bağlama zədələnib"],
                ['value' => 'TTC33', 'text' => "Səhv telefon nömrəsi"],
                ['value' => 'TTC30', 'text' => "Müştəri bağlamadan imtina etdi"],
            ]),
            'status' => [
                0 => 'Sifariş olundu',
                1 => 'Sifariş qəbul olunub',
                2 => 'Kuryer təyin edilmişdir',
                3 => 'Götürüldü',
                4 => 'Təslim edildi',
                5 => 'Ləğv edildi',
                7 => 'Çatdırılmadı',
                6 => 'Done',
            ],
            'statusWithLabel' => json_encode([
                ['value' => 0, 'text' => 'Sifariş olundu'],
                ['value' => 1, 'text' => 'Sifariş qəbul olunub'],
                ['value' => 2, 'text' => 'Kuryer təyin edilmişdir'],
                ['value' => 3, 'text' => 'Götürüldü'],
                ['value' => 4, 'text' => 'Təslim edildi'],
                ['value' => 5, 'text' => 'Ləğv edildi'],
                ['value' => 7, 'text' => 'Çatdırılmadı'],
                ['value' => 6, 'text' => 'Done'],
                /*['value' => 0, 'text' => "Created By User"],
                ['value' => 1, 'text' => "Accepted"],
                ['value' => 2, 'text' => "Courier Assigned"],
                ['value' => 3, 'text' => "Sent"],
                ['value' => 4, 'text' => "Delivered"],
                ['value' => 5, 'text' => "Canceled"],
                ['value' => 6, 'text' => "Done"],
		['value' => 7, 'text' => "Not Delivered"]*/
            ]),
            'status2' => [
                0 => 'Sifariş olundu',
                1 => 'Sifariş qəbul olunub',
                101 => 'Kuryer təyin edilmişdir/Götürüldü/Çatdırılmadı',
                2 => 'Kuryer təyin edilmişdir',
                3 => 'Götürüldü',
                4 => 'Təslim edildi',
                5 => 'Ləğv edildi',
                7 => 'Çatdırılmadı',
                6 => 'Done',
                102 => 'Təslim edildi/Done',
                //'TTC47' =>  "Rescheduled with Customer",
                //'TTC48' =>  "Customer requests to change location",
                //'TTC55' =>  "Address information is incomplete",
                //'TTC37' =>  "No answer from customer",
                //'TTC36' =>  "Package Damaged",
                //'TTC33' =>  "Wrong phone number",
                //'TTC30' =>  "Parcel refused by customer",
            ],
            'status2WithLabel' => json_encode([
                ['value' => 0, 'text' => 'Sifariş olundu'],
                ['value' => 1, 'text' => 'Sifariş qəbul olunub'],
                ['value' => 2, 'text' => 'Kuryer təyin edilmişdir'],
                ['value' => 3, 'text' => 'Götürüldü'],
                ['value' => 4, 'text' => 'Təslim edildi'],
                ['value' => 5, 'text' => 'Ləğv edildi'],
                ['value' => 7, 'text' => 'Çatdırılmadı'],
                ['value' => 6, 'text' => 'Done'],
                //['value' => 'TTC47', 'text' => "Rescheduled with Customer"],
                //['value' => 'TTC48', 'text' => "Customer requests to change location"],
                //['value' => 'TTC55', 'text' => "Address information is incomplete"],
                //['value' => 'TTC37', 'text' => "No answer from customer"],
                //['value' => 'TTC36', 'text' => "Package Damaged"],
                //['value' => 'TTC33', 'text' => "Wrong phone number"],
                //['value' => 'TTC30', 'text' => "Parcel refused by customer"],
            ]),
            'statusCd' => [
                0 => 'Sifariş olundu',
                1 => 'Sifariş qəbul olunub',
                101 => 'Kuryer təyin edilmişdir/Götürüldü/Çatdırılmadı',
                2 => 'Kuryer təyin edilmişdir',
                3 => 'Götürüldü',
                4 => 'Təslim edildi',
                5 => 'Ləğv edildi',
                7 => 'Çatdırılmadı',
                //'TTC47' =>  "Rescheduled with Customer",
                //'TTC48' =>  "Customer requests to change location",
                //'TTC55' =>  "Address information is incomplete",
                //'TTC37' =>  "No answer from customer",
                //'TTC36' =>  "Package Damaged",
                //'TTC33' =>  "Wrong phone number",
                //'TTC30' =>  "Parcel refused by customer",
            ],
            'statusCdWithLabel' => json_encode([
                ['value' => 0, 'text' => 'Sifariş olundu'],
                ['value' => 1, 'text' => 'Sifariş qəbul olunub'],
                ['value' => 2, 'text' => 'Kuryer təyin edilmişdir'],
                ['value' => 3, 'text' => 'Götürüldü'],
                ['value' => 4, 'text' => 'Təslim edildi'],
                ['value' => 5, 'text' => 'Ləğv edildi'],
                ['value' => 7, 'text' => 'Çatdırılmadı'],
                //['value' => 'TTC47', 'text' => "Rescheduled with Customer"],
                //['value' => 'TTC48', 'text' => "Customer requests to change location"],
                //['value' => 'TTC55', 'text' => "Address information is incomplete"],
                //['value' => 'TTC37', 'text' => "No answer from customer"],
                //['value' => 'TTC36', 'text' => "Package Damaged"],
                //['value' => 'TTC33', 'text' => "Wrong phone number"],
                ['value' => 'TTC30', 'text' => "Parcel refused by customer"],
            ]),
            'statusCd2' => [
                2 => 'Kuryer təyin edilmişdir',
                3 => 'Götürüldü',
                4 => 'Təslim edildi',
                7 => 'Çatdırılmadı',
                //'TTC47' =>  "Rescheduled with Customer",
                //'TTC48' =>  "Customer requests to change location",
                //'TTC55' =>  "Address information is incomplete",
                //'TTC37' =>  "No answer from customer",
                //'TTC36' =>  "Package Damaged",
                //'TTC33' =>  "Wrong phone number",
                //'TTC30' =>  "Parcel refused by customer",
            ],

            'statusCd2WithLabel' => json_encode([
                ['value' => 2, 'text' => 'Kuryer təyin edilmişdir'],
                ['value' => 3, 'text' => 'Götürüldü'],
                ['value' => 4, 'text' => 'Təslim edildi'],
                ['value' => 7, 'text' => 'Çatdırılmadı'],

                //['value' => 'TTC47', 'text' => "Rescheduled with Customer"],
                //['value' => 'TTC48', 'text' => "Customer requests to change location"],
                //['value' => 'TTC55', 'text' => "Address information is incomplete"],
                //['value' => 'TTC37', 'text' => "No answer from customer"],
                //['value' => 'TTC36', 'text' => "Package Damaged"],
                //['value' => 'TTC33', 'text' => "Wrong phone number"],
                //['value' => 'TTC30', 'text' => "Parcel refused by customer"],
            ]),

            'direction' => [0 => 'Aseshop', 1 => 'Import', 2 => 'Export', 3 => 'Non Aseshop', 4 => 'VFS'],
            'direction2' => [0 => 'Aseshop', 1 => 'Import/Export', 3 => 'Non Aseshop',4 => 'VFS'],
            'direction3' => [0 => 'Aseshop', 1 => 'Import', 2 => 'Export', 3 => 'Non Aseshop', 12 => 'Import/Export',4 => 'VFS'],

            'directionWithLabel' => '[{value:0, text: "Aseshop"},{value:1, text: "Import"}, {value:2, text:"Export"}, {value:3, text:"Non Aseshop"}, {value:4, text:"VFS"}]',
            'invoice' => [0 => '--', 1 => 'Faktura', 2 => 'Nagd'],
            'invoiceWithLabel' => '[{value:0, text: "--"},{value:1, text: "Faktura"}, {value:2, text:"Nagd"}]',
            'date_by' => [
                'courier_assigned_at' => 'by AssignedAt',
		'courier_get_at' => 'by CourierGetAt',
                'delivered_at' => 'by DeliveredAt',
                'created_at' => 'by CreatedAt',
            ],
        ],
        'request' => [
            'link' => [
                'status' => ['Active', 'Not found', 'Out of stock'],
                'statusTrans' => ['front.active', 'front.not_found', 'front.out_of_stock'],
                'statusWithLabel' => '[{value: 0, text: "Active"}, {value: 1, text: "Not found"}, {value: 2, text: "Out of stock"}]',
            ],
            'status' => ['New Order', 'Paid', 'Ordered', 'Delivered', 'Canceled', 'Accepted'],
            'statusTrans' => [
                'front.new_order',
                'front.paid',
                'front.ordered',
                'front.delivered',
                'front.canceled',
                'front.accepted',
            ],
            'statusWithLabel' => '[{value: 0, text: "New Order"}, {value: 1, text: "Paid"}, {value: 2, text: "Ordered"}, {value: 3, text: "Delivered"}, {value: 4, text: "Canceled"}, {value: 5, text: "Accepted"}]',
        ],
        'promo' => [
            'activation' => [
                1 => 'Registration',
                2 => 'Checkout page',
            ],
        ],
        'package' => [
            'label' => ['Hide', 'Show'],
            'labelWithLabel' => "{'1': 'Show'}",
            'dec' => [
                1 => 'Not Declared',
                2 => 'Ready',
                3 => 'All with Done',
            ],
            'date_by' => [
                'created_at' => 'by Creating Date',
                'scanned_at' => 'by Delivered Date',
            ],
            'discount' => [
                0 => 'No Discount',
                1 => 'Any Discount',
                2 => 'Discount',
                3 => 'Ulduzum discount',
                4 => 'Promo code',
            ],
            'paid' => [
                0 => 'No',
                1 => 'Yes',
                2 => 'POST_TERMINAL',
                3 => 'GIFT_CARD',
                4 => 'BONUS',
                8 => 'BANK_TRANSFER',
            ],
            'paid2' => [
                0 => 'No',
                1 => 'Yes',
                2 => 'CASH',
                3 => 'POST_TERMINAL',
                4 => 'GIFT_CARD',
                5 => 'BONUS',
                6 => 'PORTMANAT',
                7 => 'REFUND',
                8 => 'BANK_TRANSFER',
                9 => 'AZERPOCT',
                10 => 'KAPITAL',
            ],
            'incustoms' => [
                0 => 'Not in customs',
                1 => 'In customs',
                6 => 'In customs - Has declaration',
                8 => 'In customs - Has declaration no number',
                9 => 'In customs - Has declaration no depesh',
                2 => 'In customs - Has dec number',
                4 => 'In customs - No dec number',
                7 => 'In customs - No declaration',
                3 => 'In customs - Has depesh',
                5 => 'In customs - No depesh',
                10 => 'With errors',
            ],
            'inazerpoct' => [
                1 => 'Not in Azerpoct',
                2 => 'In Azerpoct',
            ],
            'status' => [
                6 => 'Early Declaration',
                0 => 'In Warehouse',
                7 => 'Departed',
                1 => 'Sent',
                8 => 'In Kobia',
                2 => 'In Baku',
                3 => 'Done',
                4 => 'In customs',
                5 => 'Rejected',
                41 => 'WaitingDomesticShipment',
                47 => 'WaitingForDeclaration',
                48 => 'In customs - Neutral',
            ],
            'status_for_warehouse' => [
                0 => 'In Warehouse',
                6 => 'Early Declaration',
            ],
            'unknown_status_full' => [
                0 => '---',
                1 => 'Please provide photo with visible ASE code',
                2 => 'Please add photo',
                3 => 'Please split package into 2',
                4 => 'Please split package into 3',
                5 => 'Please split package into 4',
                6 => 'Please add package to Group 1',
                7 => 'Please add package to Group 2',
                8 => 'Please add package to Group 3',
                9 => 'Please add package to Group 4',
                10 => 'Please return package',
            ],
            'unknown_status' => [
                0 => '-',
                1 => 'Invisible ASE Code',
                2 => 'No Photo',
                3 => 'Split 2',
                4 => 'Split 3',
                5 => 'Split 4',
                6 => 'Add to Group 1',
                7 => 'Add to Group 2',
                8 => 'Add to Group 3',
                9 => 'Add to Group 4',
                10 => 'Return',
            ],
            'unknownStatusWithLabel' => '[{value: 0, text: "---"}, {value: 1, text: "Invisible ASE Code"}, {value: 2, text: "No Photo"}, {value: 3, text: "Split 2"} , {value: 3, text: "Split 3"}, {value: 5, text: "Split 4"}, {value: 6, text: "Add to Group 1"}, {value: 7, text: "Add to Group 2"}, {value: 8, text: "Add to Group 3"}, {value: 9, text: "Add to Group 4"}, {value: 10, text: "Return"}]',
            'statusWithLabel' => '[{value: 0, text: "In Warehouse"}, {value: 7, text: "Departed"} , {value: 1, text: "Sent"}, {value: 8, text: "In Kobia"}, {value: 2, text: "In Baku"}, {value: 48, text: "In customs - Neutral"}, {value: 3, text: "Done"}, {value: 4, text: "In customs"}, {value: 5, text: "Rejected"}, {value: 6, text: "Early Declaration"}]',
            'statusNotPaidWithLabel' => '[{value: 0, text: "In Warehouse"}, {value: 7, text: "Departed"} , {value: 1, text: "Sent"}, {value: 8, text: "In Kobia"}, {value: 2, text: "In Baku"},{value: 3, text: "Done"}, {value: 4, text: "In customs"},{value: 48, text: "In customs - Neutral"}, {value: 5, text: "Rejected"}, {value: 6, text: "Early Declaration"}]',
            'paidWithLabel' => '[{value: 0, text: "No"}, {value: 1, text: "Yes"}, {value: 2, text: "By POST_TERMINAL"}, {value: 3, text: "By GIFT_CARD"}, {value: 4, text: "By BONUS"},{value: 8, text: "By Bank Transfer"}]',
            'brokerPaidWithLabel' => '[{value: 0, text: "No"},{value: 1, text: "Online"}, {value: 2, text: "By POST_TERMINAL"}]',
            //'paidWithLabelDebt' => '[{value: 0, text: "No"}, {value: 2, text: "Rejected"}, {value: 3, text: "By POST_TERMINAL"}]',
            'paidWithLabelDebt' => '[{value: 0, text: "No"}, {value: 1, text: "Yes"}, {value: 2, text: "Rejected"}, {value: 3, text: "By POST_TERMINAL"}]',
            'stopDebt' => '[{value: 0, text: "No"}, {value: 1, text: "Yes"}]',
            'ukr_express_status' => [
                0 => '-',
                1 => 'Added to Ukr Express',
                2 => 'Recevied',
                3 => 'Customer Assigned',
                4 => 'Packed',
                5 => 'loaded to Airbox',
                6 => 'Airbox Loaded to Container',
                8 => 'Updated from Ukr Express',
                11 => 'Reweighed',
                102 => 'Cannot change customer',
                103 => 'Cannot find user of package',
                104 => 'Cannot add package to Ukr Express',
                121 => 'Unpacked',
                122 => 'Damaged',
                123 => 'Forbidden',
                200 => 'Not Packed',
                201 => 'With Errors',
            ],
            'UkrExpressStatusWithLabel' => '[{value: 0, text: "-"}, {value: 1, text: "Added to Ukr Express"}, {value: 2, text: "Received"}, {value: 3, text: "Customer Assigned"} , {value: 4, text: "Packaed"}, {value: 5, text: "Loaded to Airbox"}, {value: 6, text: "Airbox Loaded to Container"}, {value: 8, text: "Updated from Ukr Express"}, {value: 11, text: "Reweighed"}, {value: 102, text: ""Cannot change customer}, {value: 103, text: "Cannot find user of package"}, {value: 104, text: "Cannot add package to Ukr Express"}, {value: 121, text: "Unpacked"}, {value: 122, text: "Damaged"}, {value: 123, text: "Forbidden"}, {value: 200, text: "Not Packed"}, {value: 201, text: "With Errors"}]',
        ],
        'transaction' => [
            'types' => [
                //'OUT'  => 'Out',
                'IN' => 'Deposit',
                'DEBT' => 'Debt',
            ],
            'transaction_type' => [
                'PACKAGE_DEBT' => 'Package debt',
                'TRACK_DEBT' => 'Track debt',
            ],
            'paid_for' => [
//                'PACKAGE_BALANCE' => 'Package Balance',
//                'ORDER_BALANCE'   => 'Order Balance',
                'PACKAGE' => 'PACKAGE',
                'MARKET' => 'MARKET',
                'PACKAGE_SHIPPING' => 'PACKAGE_SHIPPING',
                'COURIER_DELIVERY' => 'COURIER_DELIVERY',
                'TRACK_DELIVERY' => 'TRACK_DELIVERY',
                'TRACK_DEBT' => 'TRACK_DEBT',
                'PACKAGE_DEBT' => 'PACKAGE_DEBT',
                'TRACK_BROKER' => 'TRACK_BROKER',
                'PACKAGE_BROKER' => 'PACKAGE_BROKER',
            ],
            'paid_by' => [
                'CASH' => 'Cash',
                'MILLION' => 'MilliÖn',
                'POST_TERMINAL' => 'Post Terminal',
                'REFUND' => 'Refund',
                'PORTMANAT' => 'PortManat',
                'GIFT_CARD' => 'Gift Card',
                'OTHER' => 'Other',
                'BANK_TRANSFER' => 'Bank Transfer',
                'AZERPOCT' => 'Azer Post Office',
                'KAPITAL' => 'Kapital',
            ],
            'by' => [
                'BONUS' => 0,
                'GIFT_CARD' => 0,
                'CASH' => 1,
                'PAY_TR' => 1,
                'MILLION' => 1,
                'PORTMANAT' => 1,
                'POST_TERMINAL' => 1,
                'REFERRAL' => -1,
                'CASHBACK' => -1,
                'PACKAGE_BALANCE' => -1,
                'ORDER_BALANCE' => -1,
                'OTHER' => 1,
                'REFUND' => -1,
                'BANK_TRANSFER' => 1,
                'AZERPOCT' => 1,
                'KAPITAL' => 1,
            ],
        ],
        'track' => [
            'status' => [
                1 => 'TRACKING-RECEIVED',
                2 => 'CUSTOMER-ASSIGNED',
                3 => 'TRACKING-FORBIDDEN',
                4 => 'TRACKING-DELETED',
                5 => 'ADDED_TO_CUSTOMS',
                6 => 'NOT_ADDED_TO_CUSTOMS',
                7 => 'DECLARED_IN_CUSTOMS',
                8 => 'TRACKING_PACKED',
                9 => 'TRACKING_NOT_PACKED',
                10 => 'TRACKING_LOADED',
                11 => 'TRACKING_NOT_LOADED',
                12 => 'TRACKING_SENT',
                13 => 'TRACKING_NOT_SENT',
                14 => 'DEPESH',
                15 => 'NOT_DEPESH',
                16 => 'IN_BAKU',
                17 => 'DONE',
                18 => 'IN_CUSTOMS',
                44 => 'CUSTOM_CLEARANCE',
                25 => 'CUSTOM_COMPLETED',
                19 => 'REJECTED',
                20 => 'IN_KOBIA',
                21 => 'OUT_FOR_DELIVERY',
                22 => 'FAILED_ATTEMPT',
                23 => 'UNDELIVERED',
                24 => 'PUDO_ACCEPTED',//same with in baku, don't remove
                26 => 'NOT_ARRIVED',
                27 => 'REJECTED_IN_RC',
                28 => 'RTO',
                29 => 'REFUND',
                45 => 'WRONG PRICE',
                46 => 'IN CUSTOMS - Neutral',
                47 => 'SCL_Stopped_in_customs_overlimit',
            ],
            'statusShort' => [
                1 => 'IN WAREHOUSE',
                5 => 'ADDED_TO_CUSTOMS',
                7 => 'DECLARED_IN_CUSTOMS',
                14 => 'DEPESH',
                8 => 'TRACKING_PACKED',
                12 => 'SENT',
                18 => 'IN_CUSTOMS',
                44 => 'CUSTOM_CLEARANCE',
                25 => 'CUSTOM_COMPLETED',
                20 => 'IN KOBIA',
                16 => 'IN BAKU',
                24 => 'PUDO_ACCEPTED',//same with in baku, don't remove
                17 => 'DONE',
                19 => 'REJECTED',
                21 => 'OUT_FOR_DELIVERY',
                22 => 'FAILED_ATTEMPT',
                23 => 'UNDELIVERED',
                26 => 'NOT_ARRIVED',
                27 => 'REJECTED_IN_RC',
                28 => 'RTO',
                30 => 'COMBINED',
                31 => 'SEPARATE',
                29 => 'REFUND',
                45 => 'WRONG PRICE',
                46 => 'IN CUSTOMS - Neutral',
                47 => 'SCL_Stopped_in_customs_overlimit',
            ],
            'statusShortWithLabel' => json_encode([
                ['value' => 1, 'text' => 'IN WAREHOUSE'],
                ['value' => 5, 'text' => 'ADDED TO CUSTOMS'],
                ['value' => 7, 'text' => 'DECLARED IN CUSTOMS'],
                ['value' => 14, 'text' => 'DEPESH'],
                ['value' => 8, 'text' => 'TRACKING PACKED'],
                ['value' => 12, 'text' => 'SENT'],
                ['value' => 25, 'text' => 'CUSTOM COMPLETED'],
                ['value' => 20, 'text' => 'IN KOBIA'],
                ['value' => 16, 'text' => 'IN BAKU'],
                ['value' => 21, 'text' => 'OUT FOR DELIVERY'],
                ['value' => 22, 'text' => 'FAILED ATTEMPT'],
                ['value' => 23, 'text' => 'UNDELIVERED'],
                ['value' => 17, 'text' => 'DONE'],
                ['value' => 18, 'text' => 'STOPPED IN CUSTOMS'],
                ['value' => 44, 'text' => 'CUSTOM_CLEARANCE'],
                ['value' => 19, 'text' => 'REJECTED'],
                ['value' => 26, 'text' => 'NOT ARRIVED'],
                ['value' => 27, 'text' => 'REJECTED IN RC'],
                ['value' => 28, 'text' => 'RTO'],
                ['value' => 30, 'text' => 'COMBINED'],
                ['value' => 31, 'text' => 'SEPARATE'],
                ['value' => 29, 'text' => 'REFUND'],
                ['value' => 45, 'text' => 'WRONG PRICE'],
                ['value' => 46, 'text' => 'IN CUSTOMS - Neutral'],
                ['value' => 47, 'text' => 'SCL Stopped in customs overlimit'],
            ]),
            'paid' => [
                0 => 'No',
                1 => 'Yes',
            ],
            'paidWithLabel' => '[{value: 0, text: "No"}, {value: 1, text: "Yes"},{value: 4, text: "By Bonus"}]',
            'partner' => [
                1 => "iHerb",
                2 => "Wildberries",
                3 => "Ozon",
                4 => "MakeUp",
                5 => "CSE RU",
                6 => "ASE Express TR",
                7 => "China Meest",
                8 => "Gfs",
                9 => "Taobao Equick",
                10 => "VFS",
            ],
            'partnerWithLabel' => '[{value: 1, text: "iHerb"}, {value: 2, text: "Wildberries" }, {value: 3, text: "Ozon" }, {value: 4, text: "MakeUp" }, {value: 5, text: "CSE RU" }, {value: 6, text: "ASE Express TR" }, {value: 7, text: "China Meest" }]',
        ]
    ],
    'addresses' => [
        'tr' => [
            'BAHCELIEVLER BAHCELIEVLER',
            'LOGYPARK BAHCELIEVLER',
        ],

    ],
];
